### ISSUE TITLE
Model takes forever on certain accounts

### ISSUE THREAD

**Issue by TheChief0117** [wordware-ai/twitter#4]
Tried running it on a Twitter account @myrosierheart, but all it did was load endlessly, seeming like it was doing something in the background, but in reality wasn't. 
![image](https://github.com/user-attachments/assets/8c1dcc16-4ef8-47f6-8283-85bd06cc7aaa)

**Comment by Waffles7z** [comment]
here to confirm this is not a one-time issue, and is happening to multiple accounts.
![image](https://github.com/user-attachments/assets/7b7cfb62-f4d5-4d7c-a620-b66cc0f6b80c)
![image](https://github.com/user-attachments/assets/a58b9a16-2ab8-49e3-b506-2a08466a37a9)

**Comment by danny-hunt** [comment]
Hey sorry about the downtime @TheChief0117 & @Waffles7z 

We should be back up and running at 100% now and I've gone ahead and completed and unlocked your analyses too. 

https://twitter.wordware.ai/myrosierheart

https://twitter.wordware.ai/KirbyCheatFurby

https://twitter.wordware.ai/Waffle7z
